# Generated by Django 5.1 on 2024-08-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contraseña',
            new_name='password',
        ),
    ]
